# Generated by Django 3.1.2 on 2020-11-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('main_actors', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=5)),
            ],
        ),
    ]
